[package]
name = "pi_tester"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"